import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Languages, 
  Mic, 
  BookOpen, 
  Award, 
  ArrowRight, 
  Sparkles,
  Users,
  TrendingUp,
  Star,
  CheckCircle,
  Globe,
  MessageCircle,
  BookMarked,
  Volume2,
  Flag,
  Speech,
  Keyboard,
  Book,
  UserCheck
} from 'lucide-react';
import TranslationInterface from '../components/TranslationInterface';
import { useAuth } from '../contexts/AuthContext';
import ParticleBackground from '../components/ParticleBackground';
import AnimatedButton from '../components/AnimatedButton';
import { Carousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
// Removed ModernHero import
import Footer from '../components/Footer';

const languageIcons = [
  <Languages className="w-10 h-10 text-blue-500" />, // generic
  <Flag className="w-10 h-10 text-red-500" />, // flag
  <BookOpen className="w-10 h-10 text-green-500" />, // book
  <Mic className="w-10 h-10 text-purple-500" />, // mic
  <MessageCircle className="w-10 h-10 text-yellow-500" />, // chat
  <Volume2 className="w-10 h-10 text-pink-500" />, // audio
  <Keyboard className="w-10 h-10 text-indigo-500" />, // typing
  <Globe className="w-10 h-10 text-blue-400" /> // globe
];

const Home = () => {
  const { user } = useAuth();
  const navigate = useNavigate();

  // Fetch real stats from backend
  const [stats, setStats] = useState([
    { number: '...', label: 'Active Users', icon: Users },
    { number: '...', label: 'Translations', icon: Languages },
    { number: '...', label: 'Accuracy Rate', icon: TrendingUp },
    { number: '...', label: 'User Rating', icon: Star }
  ]);
  const [loadingStats, setLoadingStats] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const res = await fetch('/api/stats');
        const data = await res.json();
        setStats([
          { number: data.users, label: 'Active Users', icon: Users },
          { number: data.translations, label: 'Translations', icon: Languages },
          { number: data.accuracy + '%', label: 'Accuracy Rate', icon: TrendingUp },
          { number: data.rating, label: 'User Rating', icon: Star }
        ]);
      } catch (e) {
        // fallback to placeholders
      } finally {
        setLoadingStats(false);
      }
    };
    fetchStats();
  }, []);

  // Update features to reflect current app capabilities
  const features = [
    {
      icon: Languages,
      title: 'AI-Powered Translation',
      description: 'Instantly translate text and documents (PDF, DOCX, TXT) between Sinhala, English, and Tamil using advanced AI. Includes voice input and text-to-speech.',
      color: 'from-green-500 to-blue-500'
    },
    {
      icon: Award,
      title: 'Dynamic Quizzes',
      description: 'Test your vocabulary and grammar with quizzes generated by AI based on your learning history and vocabulary.',
      color: 'from-yellow-500 to-orange-500'
    },
    {
      icon: BookMarked,
      title: 'Progress & Achievements',
      description: 'Track your XP, streaks, and achievements. View your translation and quiz history with advanced filtering and search.',
      color: 'from-purple-600 to-pink-500'
    },
    {
      icon: UserCheck,
      title: 'Modern Authentication',
      description: 'Sign up or log in with Google or email. Includes a robust forgot password flow with email OTP verification.',
      color: 'from-blue-600 to-purple-600'
    }
  ];

  const testimonials = [
    {
      name: 'Priya Sharma',
      role: 'Language Teacher',
      content: 'LangBridge has revolutionized how I teach my students. The AI-powered examples are incredibly helpful!',
      rating: 5,
      avatar: 'PS'
    },
    {
      name: 'Kasun Perera',
      role: 'Student',
      content: 'The voice recognition feature is amazing. I can practice pronunciation and get instant feedback.',
      rating: 5,
      avatar: 'KP'
    },
    {
      name: 'Meera Patel',
      role: 'Business Professional',
      content: 'Perfect for my daily work. The translations are accurate and the interface is so user-friendly.',
      rating: 5,
      avatar: 'MP'
    }
  ];

  const FeatureCard = ({ icon: Icon, title, description, color, delay = 0 }) => (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay }}
      whileHover={{ scale: 1.05, y: -10 }}
      className="group relative overflow-hidden card-premium p-8 cursor-pointer"
    >
      <div className={`absolute inset-0 bg-gradient-to-br ${color} opacity-0 group-hover:opacity-5 transition-opacity duration-300 rounded-2xl`} />
      
      <div className="relative z-10">
        <motion.div
          initial={{ scale: 0, rotate: -180 }}
          whileInView={{ scale: 1, rotate: 0 }}
          transition={{ duration: 0.5, delay: delay + 0.2 }}
          className={`w-20 h-20 bg-gradient-to-r ${color} rounded-2xl flex items-center justify-center mb-6 shadow-lg group-hover:shadow-xl transform-gpu transition-all duration-300 group-hover:scale-110`}
        >
          <Icon className="w-8 h-8 text-white" />
        </motion.div>
        
        <motion.h3
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: delay + 0.4 }}
          className="text-xl font-bold text-gray-800 dark:text-gray-100 mb-4"
        >
          {title}
        </motion.h3>
        
        <motion.p
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: delay + 0.6 }}
          className="text-base text-gray-600 dark:text-gray-400 leading-relaxed"
        >
          {description}
        </motion.p>
      </div>
      
      <div className={`absolute inset-0 bg-gradient-to-r ${color} opacity-0 group-hover:opacity-10 blur-xl transition-all duration-500 rounded-2xl`} />
    </motion.div>
  );

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 relative overflow-hidden">
      {/* HERO SECTION */}
      <section className="relative py-24 md:py-32 bg-gradient-to-br from-blue-50 via-white to-purple-100 dark:from-gray-900 dark:via-gray-800 dark:to-blue-900 overflow-hidden">
        <ParticleBackground density={30} />
        <div className="absolute inset-0 flex flex-wrap justify-center items-center opacity-10 pointer-events-none select-none">
          {/* Language icons as background */}
          {languageIcons.map((icon, idx) => (
            <div key={idx} className="m-8 animate-float-slow">
              {icon}
            </div>
          ))}
        </div>
        <div className="relative z-10 max-w-4xl mx-auto px-4 text-center">
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
            className="text-5xl md:text-7xl font-extrabold text-gray-900 dark:text-white mb-6 drop-shadow-lg"
                >
            Bridge Languages. <span className="text-gradient">Empower Minds.</span>
              </motion.h1>
              <motion.p 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.2 }}
            className="text-xl md:text-2xl text-gray-700 dark:text-gray-200 mb-8 max-w-2xl mx-auto"
              >
        AI-powered translation, document upload, dynamic quizzes, voice features, and modern progress tracking for Sinhala, English, and Tamil.
      </motion.p>
          <div className="flex flex-col sm:flex-row justify-center gap-4 mb-8">
            {!user && (
            <AnimatedButton onClick={() => navigate('/register')} variant="primary" size="lg">
                  Get Started Free
                </AnimatedButton>
            )}
            <Link to="/translate">
              <AnimatedButton variant="secondary" size="lg">
                Try Translator <ArrowRight className="inline w-5 h-5 ml-2" />
                </AnimatedButton>
            </Link>
          </div>
          <div className="flex flex-wrap justify-center gap-4 mt-6">
            {/* Supported language icons */}
            <span className="inline-flex items-center px-4 py-2 bg-blue-100 dark:bg-blue-900/30 rounded-full text-blue-700 dark:text-blue-200 font-semibold text-lg">
              🇱🇰 Sinhala
            </span>
            <span className="inline-flex items-center px-4 py-2 bg-green-100 dark:bg-green-900/30 rounded-full text-green-700 dark:text-green-200 font-semibold text-lg">
              🇬🇧 English
            </span>
            <span className="inline-flex items-center px-4 py-2 bg-pink-100 dark:bg-pink-900/30 rounded-full text-pink-700 dark:text-pink-200 font-semibold text-lg">
              🇮🇳 Tamil
            </span>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-20 bg-white/50 dark:bg-gray-800/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {loadingStats
              ? Array(4).fill(0).map((_, index) => (
                  <div key={index} className="text-center animate-pulse">
                    <div className="w-20 h-20 bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4" />
                    <div className="h-8 w-16 bg-gray-200 dark:bg-gray-700 rounded mx-auto mb-2" />
                    <div className="h-4 w-24 bg-gray-200 dark:bg-gray-700 rounded mx-auto" />
                  </div>
                ))
              : stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="text-center group"
              >
                <motion.div 
                  className="w-20 h-20 bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-glow group-hover:shadow-2xl transition-all duration-300"
                  whileHover={{ scale: 1.1, rotate: 5 }}
                >
                  <stat.icon className="w-8 h-8 text-white" />
                </motion.div>
                <motion.div 
                  className="text-4xl font-bold text-gradient mb-2"
                  whileHover={{ scale: 1.1 }}
                >
                  {stat.number}
                </motion.div>
                <div className="text-gray-600 dark:text-gray-400 font-medium">
                  {stat.label}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white/50 dark:bg-gray-800/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-center mb-16"
          >
            <h2 className="text-5xl md:text-6xl font-bold mb-6">
              <span className="text-gradient">Powerful Features</span>
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
              Everything you need for effective language learning and translation
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <FeatureCard
                key={index}
                icon={feature.icon}
                title={feature.title}
                description={feature.description}
                color={feature.color}
                delay={index * 0.2}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Translation Interface */}
      <section className="py-20 bg-gray-50 dark:bg-gray-900 relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-center mb-16"
          >
            <h2 className="text-5xl md:text-6xl font-bold mb-6">
              <span className="text-gradient">Try Our AI Translator</span>
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
              Experience the power of AI-driven translation with voice recognition,
              example generation, and real-time processing
            </p>
          </motion.div>

          <TranslationInterface />
        </div>
      </section>

      {/* HOW IT WORKS SECTION */}
      <section className="py-20 bg-gradient-to-br from-blue-50 to-purple-100 dark:from-gray-900 dark:to-blue-900">
        <div className="max-w-5xl mx-auto px-4">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-5xl font-bold text-center mb-12 text-gradient"
          >
            How It Works
          </motion.h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="flex flex-col items-center text-center">
              <UserCheck className="w-14 h-14 text-blue-500 mb-4" />
              <h3 className="text-xl font-semibold mb-2">Sign Up or Log In</h3>
              <p className="text-gray-600 dark:text-gray-300">Create your free account with Google or email. Forgot password? Use email OTP to reset securely.</p>
            </div>
            <div className="flex flex-col items-center text-center">
              <Languages className="w-14 h-14 text-green-500 mb-4" />
              <h3 className="text-xl font-semibold mb-2">Translate Instantly</h3>
              <p className="text-gray-600 dark:text-gray-300">Translate text or upload documents. Use voice input or text-to-speech for hands-free experience.</p>
            </div>
            <div className="flex flex-col items-center text-center">
              <Award className="w-14 h-14 text-purple-500 mb-4" />
              <h3 className="text-xl font-semibold mb-2">Track Progress & Quiz</h3>
              <p className="text-gray-600 dark:text-gray-300">Take AI-generated quizzes, view your history, and track your XP, streaks, and achievements.</p>
            </div>
          </div>
        </div>
      </section>

      {/* SUPPORTED LANGUAGES SECTION */}
      <section className="py-20 bg-white/70 dark:bg-gray-800/70">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <motion.h2
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-5xl font-bold mb-8 text-gradient"
          >
            Supported Languages
          </motion.h2>
          <div className="flex flex-wrap justify-center gap-8">
            <div className="flex flex-col items-center">
              <span className="text-6xl">🇱🇰</span>
              <span className="mt-2 text-lg font-semibold">Sinhala</span>
                </div>
            <div className="flex flex-col items-center">
              <span className="text-6xl">🇬🇧</span>
              <span className="mt-2 text-lg font-semibold">English</span>
                </div>
            <div className="flex flex-col items-center">
              <span className="text-6xl">🇮🇳</span>
              <span className="mt-2 text-lg font-semibold">Tamil</span>
                </div>
          </div>
        </div>
      </section>

      {/* Testimonials Carousel */}
      <section className="py-20 bg-white/70 dark:bg-gray-800/70 backdrop-blur-sm">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
            >
            <h2 className="text-4xl md:text-5xl font-bold mb-4 text-gradient">What Our Users Say</h2>
            <p className="text-lg text-gray-600 dark:text-gray-300">Real feedback from language learners and professionals</p>
          </motion.div>
          <Carousel
            showThumbs={false}
            showStatus={false}
            infiniteLoop
            autoPlay
            interval={6000}
            className="rounded-2xl shadow-2xl bg-white/80 dark:bg-gray-900/80"
          >
            {testimonials.map((t, idx) => (
              <div key={idx} className="flex flex-col items-center py-8 px-4">
                <div className="w-16 h-16 rounded-full bg-gradient-to-r from-blue-500 to-purple-600 flex items-center justify-center mb-4 text-white text-2xl font-bold">
                  {t.avatar}
                </div>
                <p className="text-xl text-gray-800 dark:text-gray-100 mb-4">“{t.content}”</p>
                <div className="flex items-center gap-2 mb-2">
                  {[...Array(t.rating)].map((_, i) => <Star key={i} className="w-5 h-5 text-yellow-400" />)}
                </div>
                <div className="text-gray-600 dark:text-gray-400 font-medium">{t.name}, {t.role}</div>
              </div>
            ))}
          </Carousel>
        </div>
      </section>
          
      {/* CTA SECTION */}
      {!user && (
        <section className="py-20 bg-gradient-to-br from-blue-600 to-purple-600 text-white text-center">
          <div className="max-w-2xl mx-auto px-4">
            <h2 className="text-4xl md:text-5xl font-bold mb-6">Ready to Start Your Language Journey?</h2>
            <p className="text-xl mb-8">Join thousands of learners and unlock new opportunities with Sinhala, English, and Tamil.</p>
            <AnimatedButton onClick={() => navigate('/register')} variant="light" size="xl">
              Get Started Free
            </AnimatedButton>
          </div>
        </section>
      )}

      {/* FAQ SECTION */}
      <section className="py-20 bg-gradient-to-br from-white to-blue-50 dark:from-gray-900 dark:to-gray-800">
        <div className="max-w-3xl mx-auto px-4">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-5xl font-bold text-center mb-10 text-gradient"
          >
            Frequently Asked Questions
          </motion.h2>
          <div className="space-y-4">
            {[{
              q: 'Is LangBridge free to use?',
              a: 'Yes! You can get started and use all main features for free. Premium features may be added in the future.'
            }, {
              q: 'Which languages are supported?',
              a: 'Sinhala, English, and Tamil are fully supported for text and document translation.'
            }, {
              q: 'Can I translate documents?',
              a: 'Yes, you can upload PDF, DOCX, or TXT files for instant translation.'
            }, {
              q: 'How do I reset my password?',
              a: 'Use the Forgot Password link on the login page. You will receive an OTP by email to reset your password securely.'
            }, {
              q: 'How do quizzes work?',
              a: 'Quizzes are generated dynamically by AI based on your vocabulary and translation history.'
            }].map((item, idx) => (
              <details key={idx} className="bg-white dark:bg-gray-800 rounded-xl shadow p-4 group">
                <summary className="font-semibold text-lg cursor-pointer group-open:text-blue-600 transition-colors">{item.q}</summary>
                <p className="mt-2 text-gray-600 dark:text-gray-300">{item.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* NEWSLETTER SIGNUP SECTION */}
      <section className="py-16 bg-gradient-to-br from-blue-50 to-purple-100 dark:from-gray-900 dark:to-blue-900">
        <div className="max-w-xl mx-auto px-4 text-center">
          <h3 className="text-2xl md:text-3xl font-bold mb-4 text-gradient">Stay Updated!</h3>
          <p className="mb-6 text-gray-600 dark:text-gray-300">Get language tips, updates, and special offers straight to your inbox.</p>
          <form className="flex flex-col sm:flex-row gap-4 justify-center">
            <input type="email" placeholder="Your email address" className="px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-400 flex-1" />
            <button type="submit" className="px-6 py-3 rounded-lg bg-blue-600 text-white font-semibold hover:bg-blue-700 transition">Subscribe</button>
          </form>
        </div>
      </section>

      {/* FOOTER */}
      <Footer />
    </div>
  );
};

export default Home;